name: Linting and Formatting Checks

on:
  workflow_call:

jobs:
  check_linting_and_formatting:
    name: Check Linting and Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - run: npm ci
      - run: npm run lint
      - run: npm run fmt:check
