name: Workflows Pipeline

on:
  push:
  pull_request:

jobs:
  tests:
    secrets: inherit
    uses: ./.github/workflows/tests.yaml
  linting_and_formatting:
    uses: ./.github/workflows/linting-and-formatting.yaml
